services:
  app:
    image: ${APP_IMAGE:-ghcr.io/ttg-club/core-app-${ENV_TYPE:?err}}
    ports:
      - ${APP_PORT:-3000}:3000
    profiles:
      - app
      - all
    restart: unless-stopped
    environment:
      NUXT_API_URL: ${API_LOCAL_URL:?err}:${API_PORT:?err}
      NUXT_API_TOKEN: ${API_TOKEN:?err}
      NUXT_API_SECRET: ${API_SECRET:?err}
      NUXT_SITE_INDEXABLE: ${APP_SITE_INDEXABLE:-false}
      NUXT_S3_ENDPOINT: ${S3_ENDPOINT:?err}
      NUXT_S3_REGION: ${S3_REGION:?err}
      NUXT_S3_BUCKET: ${S3_BUCKET:?err}
      NUXT_S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY:?err}
      NUXT_S3_SECRET_ACCESS_KEY: ${S3_SECRET_KEY:?err}
