services:
  db-api:
    image: postgres:17
    volumes:
      - ../db/api:/var/lib/postgresql/data
    ports:
      - ${API_POSTGRES_PORT:-54322}:5432
    profiles:
      - api
      - all
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${API_POSTGRES_DB:?err} -U ${API_POSTGRES_USERNAME:?err}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: ${API_POSTGRES_DB:?err}
      POSTGRES_USER: ${API_POSTGRES_USERNAME:?err}
      POSTGRES_PASSWORD: ${API_POSTGRES_PASSWORD:?err}

  api:
    image: ${API_IMAGE:-ghcr.io/ttg-club/core-api-${ENV_TYPE:?err}}
    depends_on:
      db-api:
        condition: service_healthy
        restart: true
    ports:
      - ${API_PORT:-8080}:8080
    profiles:
      - api
      - all
    restart: unless-stopped
    environment:
      APP_URL: ${APP_URL:?err}
      APP_LOCAL_URL: ${APP_LOCAL_URL:?err}:3000
      API_TOKEN: ${API_TOKEN:?err}
      API_SECRET: ${API_SECRET:?err}
      SPRING_PROFILES_ACTIVE: ${ENV_TYPE:?err}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-api:5432/${API_POSTGRES_DB:?err}
      SPRING_DATASOURCE_USERNAME: ${API_POSTGRES_USERNAME:?err}
      SPRING_DATASOURCE_PASSWORD: ${API_POSTGRES_PASSWORD:?err}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD:?err}

