services:
  app:
    image: ${APP_IMAGE:-magistrus/ttg-app-${ENV_TYPE:?err}}
    ports:
      - ${APP_PORT:-3000}:3000
    profiles:
      - app
      - all
    restart: unless-stopped
    environment:
      NUXT_API_URL: ${API_LOCAL_URL:?err}:${API_PORT:?err}
      NUXT_API_TOKEN: ${API_TOKEN:?err}
      NUXT_API_SECRET: ${API_SECRET:?err}
      NUXT_SITE_INDEXABLE: ${APP_SITE_INDEXABLE:-false}
