services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-network
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    environment:
      - TZ=UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ./certs/letsencrypt:/certs/letsencrypt
      - ./certs/paid:/certs/paid:ro
      - ./config:/config:ro
      - ./logs:/var/log/traefik

networks:
  traefik-network:
    name: traefik-network
    driver: bridge
    external: false
