services:
  5e24-prod-app:
    image: ${APP_IMAGE:?err}
    profiles:
      - app
      - all
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      - traefik.http.services.5e24-prod-app.loadbalancer.server.port=3000
    networks:
      - 5e24-prod-network
      - traefik-network
    environment:
      NUXT_SITE_URL: https://${DOMAIN:?err}
      NUXT_SITE_INDEXABLE: ${APP_SITE_INDEXABLE:-false}
      NITRO_API_URL: http://5e24-prod-api:8080
      NITRO_API_TOKEN: ${API_TOKEN:?err}
      NITRO_API_SECRET: ${API_SECRET:?err}
      NITRO_S3_ENDPOINT: ${S3_ENDPOINT:?err}
      NITRO_S3_REGION: ${S3_REGION:?err}
      NITRO_S3_BUCKET: ${S3_BUCKET:?err}
      NITRO_S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY:?err}
      NITRO_S3_SECRET_ACCESS_KEY: ${S3_SECRET_KEY:?err}
